Homework module1 task1
htmlacademy-vue/1842585-pizza-1 pull request #2
Opened 2021-07-04 17:53 UTC by artidy

Created static home page

2021-07-04 18:31 UTC, Djaler requested changes
Много кода, про который в задаче не сказано, нужно лишнее убрать

2021-07-04 18:31 UTC, Djaler commented on template/build/cart.html
> +<!DOCTYPE html>
не нужно коммитить template/build

2021-07-04 18:31 UTC, Djaler commented on src/backend/package-lock.json
> +  "lockfileVersion": 2,
изменения package-lock тоже. чтобы они не менялись - можно использовать команду npm ci вместо npm install. Ну или просто не коммитить их

2021-07-04 18:31 UTC, Djaler commented on src/frontend/.eslintrc.js
> +    "quotes": ["warn", "single"],
думаю, не стоит менять конфигурацию линтера

2021-07-04 18:31 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +              :key="index"
в качестве ключа лучше использовать уникальное поле объекта. в нашем случае - name

2021-07-04 18:31 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +              v-for="(pizzaItem, index) in pizza.dough"
ну и pizzaItem не совсем удачное имя. мы же перебираем разные виды теста

2021-07-04 18:31 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                :value="pizzaItem.price"
значением этого инпута должно быть light/large, а не цена. дальше такие же моменты встречаются

2021-07-04 18:31 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                    :style="`--ingridient-img: url(${ingredient.image})`"
не вижу в оригинальной верстке упоминаний этих стилей

2021-07-04 18:31 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                    class="filling filling--ingridient"
у этого span должен динамически задаваться класс в зависимости от ингридиента (filling--mushrooms, filling--cheddar, и т.д.)

2021-07-04 18:31 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +              :class="`dough__input--${ pizzaItem.name === 'Тонкое' ?
такую логику не стоит держать в шаблоне, нужно выносить наружу

2021-07-04 18:31 UTC, Djaler commented on src/frontend/src/layouts/AppLayoutMainSidebar.vue
> +<template>
в задании про эти файлы ничего не сказано, зачем они тут? это не из следующих заданий код?

2021-07-05 03:18 UTC, artidy commented on src/frontend/src/views/Index.vue
> +              v-for="(pizzaItem, index) in pizza.dough"
Можете предложить какие-то варианты?

2021-07-05 03:22 UTC, artidy commented on src/frontend/src/views/Index.vue
> +                :value="pizzaItem.price"
Я понимаю что по макету там значения light/large, но по итогу мне придется туда добавлять стоимость этой позиции, чтобы посчитать итоговую стоимость пиццы. И кстати json файл сделан так, что там нет значения light/large  и тут приходится добавлять условие item === "Большая" ? "large" : "light" - что по мне кажется не совсем правильно. Предложите свои варианты решения?

2021-07-05 03:29 UTC, artidy commented on src/frontend/src/views/Index.vue
> +                    :style="`--ingridient-img: url(${ingredient.image})`"
С этим пунктом вообще интересно, мне надо циклом в шаблон добавить ингридиенты, но в макете к каждому ингридиенту с помощью псевдоэлемента :before добавлено изображение и оно так же зависит от названия класса, но в файле json нет названий на английском, но там есть изображение, я попробовал это изображение добавлять с помощью тега  img, верстка поехала, но я не знаю способов как у псевдоселектора :before поменять изображение, пришлось добавить новый класс в котором есть переменная и через нее я смог добавить изображение каждому элементу. Объясните мне есть ли другие варианты решения этого вопроса?

2021-07-05 03:43 UTC, closed without merging

2021-07-05 05:16 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +              v-for="(pizzaItem, index) in pizza.dough"
я бы использовал просто `dough`

2021-07-05 05:20 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                :value="pizzaItem.price"
Ну, в контексте текущего задания там такие значения, так что я бы их и вставлял.

Другие студенты делают определяют наборы констант и функции, которые расширяют данные из исходного json.
Посмотри, как это сделано в учебном проекте - https://github.com/htmlacademy-vue/VueWork/blob/v1/src/frontend/src/common/constants.js
https://github.com/htmlacademy-vue/VueWork/blob/e5075af79c68e75182a3b4492a59d1779d3fe879/src/frontend/src/common/helpers.js#L26

2021-07-05 05:30 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                    :style="`--ingridient-img: url(${ingredient.image})`"
хм, если честно, проглядел сперва момент, что в макете изображения подключены таки образом. Думаю, стоит уточнить у авторов, допускается ли в этом случае изменение оригинальной верстки, так как данные приходят не в том виде.