Разбивка компонента «Конструктор пиццы» на мелкие компоненты
htmlacademy-vue/1842585-pizza-1 pull request #4
Opened 2021-07-09 17:08 UTC by artidy

2021-07-09 18:17 UTC, Djaler requested changes

2021-07-09 18:17 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +      size.type = sizeTypes[size.multiplier];
вот тут есть нюанс, который легко не заметить, но он может привести к трудноуловимым проблемам. sizesList - проп. И внутри map ты модифицируешь его элементы, таким образом модифицируя переданный проп. Если бы ты модифицировал напрямую sizesList - вью бы выдал предупреждение, но тут это происходит совсем неявно.
Чтобы избежать модификации можно воспользоваться spread оператором или Object.assign, чтобы функция внутри map создавала новый объект, а не модифицировала существующий

2021-07-09 18:17 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                :styleText="`--ingridient-img: url(${ingredient.image})`"
мне кажется, так передавать стиль в компонент - нарушение его инкапсуляции. Правильнее будет передавать туда непосредственно url изображения, а компонент уже сам должен применить стиль

2021-07-09 18:17 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                :styleText="`--ingridient-img: url(${ingredient.image})`"
ну или в данном случае можно просто поставить style на компонент SelectorItem, так как нам нужно просто установить css-переменную

2021-07-09 18:17 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    drop(transferData) {
если я правильно понимаю, в контексте этого задания компоненты уже должны быть динамическими. то есть, все выборы ингридиентов и других опций должны отражаться фиксироваться в Index и отражаться здесь, в просмотре пиццы

2021-07-09 18:19 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +let result = {
объект должен находиться в данных компонента, а не вне

2021-07-09 18:20 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +    background-image: var(--ingridient-img);
и ещё заметил, что изображения ингредиентов не загружаются, потому что отсутствуют в public

2021-07-09 22:15 UTC, artidy commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    drop(transferData) {
Сделал изменение пиццы, но получается в проекте не хватает стилей для нормального размера пиццы, что делать с этим?

2021-07-10 05:36 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    drop(transferData) {
Можно посмотреть в свежей версии каркаса проекта. Может быть уже поправили этот момент. Если нет, то стоит сообщить об этом авторам. Пока можно, думаю, подставить стили от другого размера пиццы

2021-07-10 06:58 UTC, artidy commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    drop(transferData) {
Разобрался это не размер пиццы, это толщина теста.

2021-07-10 13:04 UTC, Djaler requested changes

2021-07-10 13:04 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +export default {
Из ТЗ:

В случае если количество ингредиента на пицце равно 3-м, кнопка + становится неактивной, также отключается возможность переноса ингредиента на пиццу.
В случае если количество ингредиента на пицце равно 0, кнопка - становится неактивной.

Нужно добавить такую логику

2021-07-10 13:04 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +          <BuilderPriceCounter />
3.2.5 Итоговая цена пиццы
Итоговая цена формируется исходя из добавленных ингредиентов и применённых параметров теста, размера и соуса.

Этого момента тоже не хватает

2021-07-10 13:04 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +    changed(transferData) {
хочется разделить вот этот обработчик событий на отдельные, для разных частей конструктора

2021-07-10 13:04 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +  name: "ItemCounter",
Для таких компонентов хочется видеть взаимодействие через v-model

2021-07-10 13:04 UTC, Djaler commented on src/frontend/src/common/components/RadioButton.vue
> +  name: "RadioButton",
Посмотри пример, как удобно реализуется кастомный radio-button, чтобы с ним работать через v-model https://gist.github.com/Jonarod/8553d88b1b0d1e1898ff1b5c951b00cc

2021-07-12 12:50 UTC, artidy commented on src/frontend/src/common/components/ItemCounter.vue
> +export default {
Такой логики я не вижу в домашнем задании

2021-07-12 12:51 UTC, artidy commented on src/frontend/src/views/Index.vue
> +          <BuilderPriceCounter />
По итоговой цене тоже в домашнем задании ничего не сказано

2021-07-12 12:52 UTC, artidy commented on src/frontend/src/views/Index.vue
> +    changed(transferData) {
Когда у всех элементов принцип один и тот же, зачем дублировать?

2021-07-12 12:52 UTC, artidy commented on src/frontend/src/common/components/ItemCounter.vue
> +  name: "ItemCounter",
v-model будет в 3 разделе еще не проходили

2021-07-12 12:53 UTC, artidy commented on src/frontend/src/common/components/RadioButton.vue
> +  name: "RadioButton",
Это будет в 3 разделе

2021-07-12 12:54 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +          <BuilderPriceCounter />
Там написано:
```
Выполненные пункты ТЗ
п. 3.2
п. 3.7
```

2021-07-12 12:55 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +  name: "ItemCounter",
окей

2021-07-12 12:55 UTC, Djaler commented on src/frontend/src/common/components/RadioButton.vue
> +  name: "RadioButton",
окей

2021-07-12 12:55 UTC, artidy commented on src/frontend/src/views/Index.vue
> +          <BuilderPriceCounter />
Так в самом дз не сказано

2021-07-12 12:56 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +    changed(transferData) {
ну как минимум, сейчас этот обработчик выполняет две совершенно разные вещи - обрабатывает работу с ингридиентами и с другими настройками пиццы. Это точно стоит разнести

2021-07-12 13:00 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +          <BuilderPriceCounter />
Можешь, конечно, уточнить этот момент у авторов. Но, по-моему, раз указаны в задании конкретные пункты ТЗ, значит они должны быть целиком покрыты

2021-07-12 13:29 UTC, artidy commented on src/frontend/src/common/components/ItemCounter.vue
> +export default {
Прописываю disabled, но кнопка все равно доступна

2021-07-12 13:56 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +export default {
в смысле, отображение не меняется, или всё равно клик фиксируется?

2021-07-12 13:59 UTC, artidy commented on src/frontend/src/common/components/ItemCounter.vue
> +export default {
Клик по кнопке визуально отображается, но программно отключен, стили нашел какие-то, но они тоже не сработали, визуально будто работает кнопка.

2021-07-12 14:02 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +export default {
Да, там что-то не так со стилями. Можешь поправить в src/assets/scss/blocks/counter.scss, поубирать `#{el}`. Тогда нормально сформируются селекторы для классов вида `counter__button--minus--disabled`/`counter__button--plus--disabled`. Соответственно, их надо добавлять на кнопки по условию (вместе с атрибутом disabled)

2021-07-12 16:05 UTC, artidy commented on src/frontend/src/common/components/ItemCounter.vue
> +export default {
Так по идее лишние файлы нельзя исправлять)

2021-07-12 16:08 UTC, artidy commented on src/frontend/src/views/Index.vue
> +          <BuilderPriceCounter />
Пункт 3.7 - Отображается на всех страницах сайта:

— если пользователь неавторизован: отображается ссылка для входа. При нажатии осуществляется переход на страницу авторизации; - **еще не делали страницу авторизации, так что этот пункт выполнить не могу.**

— если пользователь авторизован: отображается аватар и имя пользователя. При нажатии осуществляется переход на страницу «Мои данные». - **аналогично**

Корзина отображается для всех пользователей. Сумма формируется из стоимости всех добавленных товаров в корзину

2021-07-12 16:10 UTC, artidy commented on src/frontend/src/views/Index.vue
> +    changed(transferData) {
Эти изменения залил.

2021-07-12 16:11 UTC, artidy commented on src/frontend/src/common/components/ItemCounter.vue
> +export default {
Я добавил выбор класса и атрибут disabled, но стили менять не стал, подожду когда поправят разработчики курса.

2021-07-13 03:31 UTC, merged